#!/usr/bin/env node
// render.mjs — generate the broll registry (library + customs), resolve
// scenes, run Remotion render, copy output to ~/Desktop.
//
// Usage: node render.mjs <workspace>

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { execSync, spawnSync } from "node:child_process";

const SKILL_DIR = path.resolve(
  path.dirname(new URL(import.meta.url).pathname),
  ".."
);
const LIB_DIR = path.join(SKILL_DIR, "motion-library");
const MIN_FREE_GB = 1.5;

function fail(msg) {
  console.error(`❌ ${msg}`);
  process.exit(1);
}

function preflight(workspace) {
  // 1. Disk space — render needs ~1-2GB for Chromium download + frame cache
  try {
    const out = execSync(`df -k "${workspace}" | tail -1 | awk '{print $4}'`)
      .toString().trim();
    const freeKB = parseInt(out, 10);
    const freeGB = freeKB / 1024 / 1024;
    if (freeGB < MIN_FREE_GB) {
      fail(
        `Only ${freeGB.toFixed(2)}GB free at ${workspace}. Need ≥${MIN_FREE_GB}GB.\n` +
        `   Free space first. Common culprits:\n` +
        `     rm -rf ~/.claude.backup-* (large ad-hoc backups)\n` +
        `     rm -rf <other-vibe-edit-project>/node_modules (regenerable, ~450MB each)\n` +
        `     rm /tmp/react-motion-render* (stale render frames)`
      );
    }
    console.log(`✓ disk: ${freeGB.toFixed(2)}GB free`);
  } catch (e) {
    console.error(`(disk check failed: ${e.message} — proceeding without)`);
  }

  // 2. Workspace integrity
  const required = [
    "project.json",
    "package.json",
    "src/index.tsx",
    "src/Root.tsx",
    "src/Vertical.tsx",
    "scenes.json",
    "captions.json",
    "public/source.mp4",
  ];
  for (const f of required) {
    if (!fs.existsSync(path.join(workspace, f))) {
      fail(`missing ${f} in workspace. Run setup-project + transcribe + plan-scenes first.`);
    }
  }
  // 3. node_modules present (Remotion installed)
  if (!fs.existsSync(path.join(workspace, "node_modules", "remotion"))) {
    fail(`node_modules missing. Run: cd ${workspace} && npm install`);
  }
  console.log(`✓ workspace files present`);
}

const workspace = path.resolve(process.argv[2] ?? ".");
if (!fs.existsSync(path.join(workspace, "project.json"))) {
  fail(`Not a vibe-edit workspace: ${workspace}`);
}
preflight(workspace);
const proj = JSON.parse(
  fs.readFileSync(path.join(workspace, "project.json"), "utf8")
);

const SCENES = JSON.parse(
  fs.readFileSync(path.join(workspace, "scenes.json"), "utf8")
);

// Validate: every broll scene needs a motion picked
const unresolved = SCENES.filter(
  (s) => s.type === "broll" && (!s.motion || s.motion === null)
);
if (unresolved.length > 0) {
  console.error(`\n❌ ${unresolved.length} b-roll scenes missing a motion choice:`);
  for (const s of unresolved) {
    console.error(`   scene ${s.i} (${s.theme}): "${s.words?.slice(0, 80)}…"`);
  }
  console.error(`\nFix: hand-edit scenes.json, set "motion": "<TemplateName>" per scene.`);
  console.error(`Catalog: ${LIB_DIR}/catalog.json`);
  process.exit(1);
}

// 1. Build scenes.resolved.json — only b-roll scenes
const resolved = SCENES.filter((s) => s.type === "broll");
fs.writeFileSync(
  path.join(workspace, "scenes.resolved.json"),
  JSON.stringify(resolved, null, 2)
);
console.log(`✓ scenes.resolved.json (${resolved.length} b-roll scenes)`);

// 1b. Resolve assets if assets.json exists, else write an empty list so
// the static `import assets from "../assets.resolved.json"` resolves.
const assetsResolvedPath = path.join(workspace, "assets.resolved.json");
const assetsConfigPath = path.join(workspace, "assets.json");
if (fs.existsSync(assetsConfigPath)) {
  const r = spawnSync(
    "node",
    [path.join(SKILL_DIR, "scripts", "match-assets.mjs"), workspace],
    { stdio: "inherit" }
  );
  if (r.status !== 0) {
    console.error("match-assets.mjs failed");
    process.exit(1);
  }
} else if (!fs.existsSync(assetsResolvedPath)) {
  fs.writeFileSync(assetsResolvedPath, "[]\n");
  console.log("✓ assets.resolved.json (empty — no assets configured)");
}

// 2. Build src/broll-registry.tsx that imports library + customs
const customDir = path.join(workspace, "src", "broll-custom");
const customFiles = fs.existsSync(customDir)
  ? fs.readdirSync(customDir).filter((f) => f.endsWith(".tsx"))
  : [];

const libNames = ["ChartConvergence", "Timeline", "ProblemSolution", "BrowserBuilds", "ClockProgress", "TierStack"];

const registry = [
  `// AUTOGENERATED by render.mjs — do not edit by hand.`,
  `// Imports motion library + any customs in src/broll-custom/.`,
  ``,
  `// Library imports — copied from skill at ${LIB_DIR}`,
  ...libNames.map(
    (n) =>
      `import { ${n} } from "./.broll-library/${n}";`
  ),
  `import type { Theme } from "./.broll-library/shared";`,
  `export type { Theme };`,
  ``,
  `// Custom imports`,
  ...customFiles.map((f) => {
    const name = f.replace(/\.tsx$/, "");
    return `import { ${name} } from "./broll-custom/${name}";`;
  }),
  ``,
  `export const LIBRARY: Record<string, React.FC<any>> = {`,
  ...libNames.map((n) => `  ${n},`),
  ...customFiles.map((f) => {
    const name = f.replace(/\.tsx$/, "");
    return `  "custom:${name}": ${name},`;
  }),
  `};`,
  ``,
];

fs.writeFileSync(
  path.join(workspace, "src", "broll-registry.tsx"),
  registry.join("\n")
);
console.log(
  `✓ src/broll-registry.tsx (${libNames.length} library + ${customFiles.length} custom)`
);

// 3. Mirror the motion library into the workspace so Remotion's webpack can
// resolve relative imports (faster + no symlink shenanigans).
const dotLib = path.join(workspace, "src", ".broll-library");
fs.rmSync(dotLib, { recursive: true, force: true });
fs.mkdirSync(dotLib, { recursive: true });
for (const f of fs.readdirSync(LIB_DIR)) {
  if (f.endsWith(".tsx") || f.endsWith(".ts")) {
    fs.copyFileSync(path.join(LIB_DIR, f), path.join(dotLib, f));
  }
}
console.log(`✓ src/.broll-library mirrored from skill`);

// 4. Run Remotion render
const outMp4 = path.join(workspace, "out", `${proj.projectName}.mp4`);
fs.rmSync(outMp4, { force: true });

console.log(`\n🎞  Rendering to ${outMp4}…`);
const r = spawnSync(
  "npx",
  [
    "remotion",
    "render",
    "src/index.tsx",
    "Vertical",
    outMp4,
    "--codec",
    "h264",
    "--crf",
    "18",
    "--audio-bitrate",
    "192k",
    "--concurrency",
    "4",
  ],
  { cwd: workspace, stdio: "inherit" }
);
if (r.status !== 0) {
  fail(
    `remotion render exited with status ${r.status}.\n` +
    `   Common causes:\n` +
    `     - disk full mid-render (rm -rf old projects' node_modules)\n` +
    `     - TypeScript error in src/Vertical.tsx or a custom in src/broll-custom/\n` +
    `     - missing asset path referenced in scenes.json or assets.json\n` +
    `     - Chromium download interrupted (re-run; first run downloads ~93MB)`
  );
}

// Post-render verification — silent failures fail loud here
if (!fs.existsSync(outMp4)) {
  fail(
    `remotion render exited 0 but no output at ${outMp4}.\n` +
    `   This is a silent failure — likely a webpack bundle error after Chromium\n` +
    `   download succeeded. Re-run; if it persists, run remotion render manually:\n` +
    `     cd ${workspace} && npx remotion render src/index.tsx Vertical out/test.mp4`
  );
}
const renderedBytes = fs.statSync(outMp4).size;
if (renderedBytes < 100_000) {
  fail(
    `Output is suspiciously small (${renderedBytes} bytes). Likely empty / corrupt.\n` +
    `   Inspect ${outMp4} — if it's a 0-byte placeholder, re-run render.`
  );
}

// 5. Copy to Desktop
const desktopOut = path.join(
  os.homedir(),
  "Desktop",
  `${proj.projectName}.mp4`
);
fs.copyFileSync(outMp4, desktopOut);
const sizeMB = (fs.statSync(desktopOut).size / 1024 / 1024).toFixed(1);
console.log(`\n✅ Done.`);
console.log(`   ${desktopOut}  (${sizeMB} MB)`);

// 6. Print per-scene motion summary
console.log(`\nMotion choices:`);
for (const s of resolved) {
  console.log(
    `   scene ${String(s.i).padStart(2, "0")} [${(s.startMs / 1000).toFixed(
      1
    )}-${((s.startMs + (s.coverDurationMs ?? s.endMs - s.startMs)) / 1000).toFixed(
      1
    )}s]  ${s.motion}  ${s.keyword ?? ""}`
  );
}
